language: ruby
cache: bundler

rvm:
  - 2.3.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - reach.viksit@gmail.com
    on_failure: change
    on_success: never

before_install: gem install bundler -v 1.11.2


